#!/usr/bin/env python3
"""Community Signals — Developer Forum Lead Extraction Tool.

Searches Hacker News and Reddit for intent signals from developer communities.
Extracts users who are actively seeking alternatives, expressing pain with
competitors, asking about problem spaces, or building DIY solutions.

Platforms:
  - Hacker News: via Algolia API (free, no auth)
  - Reddit: via Apify trudax/reddit-scraper-lite (pay-per-result)

Usage:
    python tools/community_signals.py \
        --queries queries.json \
        --days 30 \
        --output .tmp/community_signals.csv

    The queries.json file should be generated by the skill and contain:
    {
        "product": "Acme Video SDK",
        "queries": [
            {"category": "alternative_seeking", "query": "twilio alternative"},
            {"category": "competitor_pain", "query": "twilio video quality issues"},
            ...
        ],
        "subreddits": ["r/webdev", "r/VOIP", "r/programming"]
    }
"""

import argparse
import json
import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

try:
    import requests as req
except ImportError:
    print("[error] requests is required. Install with: pip install requests", file=sys.stderr)
    sys.exit(1)

import csv


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).parent.parent
TMP_DIR = PROJECT_ROOT / ".tmp"

HN_ALGOLIA_BASE = "https://hn.algolia.com/api/v1"
HN_RATE_DELAY = 0.1  # 10,000 req/hr = ~2.7/sec, 0.1s is safe

APIFY_BASE = "https://api.apify.com/v2"
APIFY_ACTOR_ID = "oAuCIx3ItNrs2okjQ"  # trudax/reddit-scraper-lite
APIFY_POLL_INTERVAL = 10  # seconds
APIFY_MAX_WAIT = 1200  # 20 minutes

# Intent signal categories
SIGNAL_CATEGORIES = {
    "alternative_seeking": {"label": "Alternative Seeking", "intent_score": 9},
    "competitor_pain": {"label": "Competitor Pain", "intent_score": 8},
    "problem_space": {"label": "Problem Space Question", "intent_score": 6},
    "tool_comparison": {"label": "Tool Comparison", "intent_score": 8},
    "diy_builtown": {"label": "DIY / Built Own Solution", "intent_score": 9},
    "scaling_challenge": {"label": "Scaling Challenge", "intent_score": 7},
    "migration_intent": {"label": "Migration Intent", "intent_score": 9},
    "budget_pricing": {"label": "Budget / Pricing Pain", "intent_score": 7},
    "feature_gap": {"label": "Feature Gap Complaint", "intent_score": 7},
}


def load_apify_key():
    """Load Apify API token from environment."""
    if load_dotenv:
        for env_path in [
            PROJECT_ROOT / ".env",
            PROJECT_ROOT.parent / ".env",
        ]:
            if env_path.exists():
                load_dotenv(env_path)
                break

    key = os.environ.get("APIFY_API_TOKEN", "")
    if not key:
        print("[error] APIFY_API_TOKEN not found in environment or .env file", file=sys.stderr)
        sys.exit(1)
    return key


def ensure_tmp():
    TMP_DIR.mkdir(exist_ok=True)


# ---------------------------------------------------------------------------
# Hacker News (Algolia API)
# ---------------------------------------------------------------------------

def hn_search(query, days=30, tags=None, hits_per_page=200):
    """Search HN via Algolia API. Returns list of hits."""
    cutoff = int((datetime.now(timezone.utc) - timedelta(days=days)).timestamp())

    params = {
        "query": query,
        "hitsPerPage": min(hits_per_page, 1000),
        "numericFilters": f"created_at_i>{cutoff}",
    }
    if tags:
        params["tags"] = tags

    try:
        resp = req.get(f"{HN_ALGOLIA_BASE}/search_by_date", params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        return data.get("hits", [])
    except Exception as e:
        print(f"[hn-error] Query '{query}' failed: {e}", file=sys.stderr)
        return []


def hn_get_user(username):
    """Fetch HN user profile."""
    try:
        resp = req.get(f"{HN_ALGOLIA_BASE}/users/{username}", timeout=10)
        if resp.status_code == 200:
            return resp.json()
    except Exception:
        pass
    return None


def extract_hn_signals(queries, days=30):
    """Search HN for all queries, extract signals.

    Args:
        queries: list of {"category": str, "query": str}
        days: lookback period

    Returns:
        list of signal dicts
    """
    signals = []
    seen_ids = set()

    for q in queries:
        query_text = q["query"]
        category = q["category"]

        # Search both stories and comments
        for tag_type in ["story", "comment"]:
            print(f"[hn] Searching {tag_type}s: '{query_text}'", file=sys.stderr)
            hits = hn_search(query_text, days=days, tags=tag_type)

            for hit in hits:
                obj_id = hit.get("objectID", "")
                if obj_id in seen_ids:
                    continue
                seen_ids.add(obj_id)

                author = hit.get("author", "")
                if not author or author == "[deleted]":
                    continue

                # Extract text content
                if tag_type == "comment":
                    text = hit.get("comment_text", "") or ""
                    title = hit.get("story_title", "") or ""
                    url = f"https://news.ycombinator.com/item?id={obj_id}"
                else:
                    text = ""
                    title = hit.get("title", "") or ""
                    url = hit.get("url", "") or f"https://news.ycombinator.com/item?id={obj_id}"

                # Clean HTML from comment text
                import re
                text_clean = re.sub(r"<[^>]+>", " ", text).strip()
                text_clean = re.sub(r"\s+", " ", text_clean)

                signals.append({
                    "platform": "hackernews",
                    "author": author,
                    "title": title,
                    "text": text_clean[:500],
                    "url": url,
                    "content_type": tag_type,
                    "category": category,
                    "category_label": SIGNAL_CATEGORIES.get(category, {}).get("label", category),
                    "score": hit.get("points", 0) or 0,
                    "num_comments": hit.get("num_comments", 0) or 0,
                    "created_at": hit.get("created_at", ""),
                    "query_matched": query_text,
                })

            time.sleep(HN_RATE_DELAY)

    print(f"[hn] Total signals extracted: {len(signals)}", file=sys.stderr)
    return signals


def enrich_hn_users(usernames):
    """Fetch HN profiles for unique usernames. Returns dict[username -> profile]."""
    profiles = {}
    for i, username in enumerate(usernames):
        profile = hn_get_user(username)
        if profile:
            profiles[username] = {
                "karma": profile.get("karma", 0),
                "about": (profile.get("about", "") or "")[:300],
                "created_at": profile.get("created_at", ""),
            }
        if (i + 1) % 50 == 0:
            print(f"[hn-profiles] {i+1}/{len(usernames)} fetched", file=sys.stderr)
        time.sleep(HN_RATE_DELAY)

    print(f"[hn-profiles] {len(profiles)}/{len(usernames)} profiles fetched", file=sys.stderr)
    return profiles


# ---------------------------------------------------------------------------
# Reddit (Apify trudax/reddit-scraper-lite)
# ---------------------------------------------------------------------------

def reddit_search_apify(queries, subreddits=None, days=30, max_posts_per_query=50,
                        max_comments_per_post=20, apify_key=None):
    """Search Reddit via Apify actor. Returns list of signal dicts."""
    if not apify_key:
        apify_key = load_apify_key()

    signals = []
    seen_ids = set()
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)

    # Build search inputs
    search_terms = [q["query"] for q in queries]
    query_category_map = {q["query"]: q["category"] for q in queries}

    # Build start URLs for subreddit-specific searches
    start_urls = []
    if subreddits:
        for sub in subreddits:
            sub_clean = sub.strip().lstrip("r/").lstrip("/")
            for search_term in search_terms:
                encoded = search_term.replace(" ", "+")
                start_urls.append({
                    "url": f"https://www.reddit.com/r/{sub_clean}/search/?q={encoded}&sort=new&t=month"
                })

    # Run actor
    actor_input = {
        "searches": search_terms,
        "maxItems": max_posts_per_query * len(search_terms) + 500,
        "searchPosts": True,
        "searchComments": False,
        "sort": "new",
        "skipComments": False,
        "maxPostCount": max_posts_per_query,
        "maxComments": max_comments_per_post,
        "includeNSFW": False,
    }

    if start_urls:
        actor_input["startUrls"] = start_urls

    print(f"[reddit] Starting Apify actor with {len(search_terms)} search terms...", file=sys.stderr)
    if subreddits:
        print(f"[reddit] Also scanning subreddits: {', '.join(subreddits)}", file=sys.stderr)

    # Start the actor run
    try:
        resp = req.post(
            f"{APIFY_BASE}/acts/{APIFY_ACTOR_ID}/runs",
            params={"token": apify_key},
            json=actor_input,
            timeout=30,
        )
        resp.raise_for_status()
        run_data = resp.json().get("data", {})
        run_id = run_data.get("id")
        print(f"[reddit] Actor run started: {run_id}", file=sys.stderr)
    except Exception as e:
        print(f"[reddit-error] Failed to start actor: {e}", file=sys.stderr)
        return []

    # Poll for completion
    elapsed = 0
    while elapsed < APIFY_MAX_WAIT:
        time.sleep(APIFY_POLL_INTERVAL)
        elapsed += APIFY_POLL_INTERVAL

        try:
            status_resp = req.get(
                f"{APIFY_BASE}/actor-runs/{run_id}",
                params={"token": apify_key},
                timeout=15,
            )
            status_data = status_resp.json().get("data", {})
            status = status_data.get("status", "")

            if status == "SUCCEEDED":
                print(f"[reddit] Actor run completed ({elapsed}s)", file=sys.stderr)
                break
            elif status in ("FAILED", "ABORTED", "TIMED-OUT"):
                print(f"[reddit-error] Actor run {status}: {status_data.get('statusMessage', '')}", file=sys.stderr)
                return []

            if elapsed % 30 == 0:
                print(f"[reddit] Waiting... status={status} ({elapsed}s)", file=sys.stderr)

        except Exception as e:
            print(f"[reddit-error] Status check failed: {e}", file=sys.stderr)
    else:
        print(f"[reddit-error] Actor run timed out after {APIFY_MAX_WAIT}s", file=sys.stderr)
        return []

    # Fetch results
    try:
        dataset_id = status_data.get("defaultDatasetId")
        results_resp = req.get(
            f"{APIFY_BASE}/datasets/{dataset_id}/items",
            params={"token": apify_key, "format": "json"},
            timeout=60,
        )
        results = results_resp.json()
        print(f"[reddit] Fetched {len(results)} items from dataset", file=sys.stderr)
    except Exception as e:
        print(f"[reddit-error] Failed to fetch results: {e}", file=sys.stderr)
        return []

    # Process results
    for item in results:
        data_type = item.get("dataType", "post")
        item_id = item.get("id", item.get("parsedId", ""))

        if item_id in seen_ids:
            continue
        seen_ids.add(item_id)

        author = item.get("username", "")
        if not author or author in ("[deleted]", "[removed]", "AutoModerator"):
            continue

        # Filter by date
        created_str = item.get("createdAt", "")
        if created_str:
            try:
                created_dt = datetime.fromisoformat(created_str.replace("Z", "+00:00"))
                if created_dt < cutoff:
                    continue
            except (ValueError, TypeError):
                pass

        # Determine category — match against query terms
        title = item.get("title", "") or ""
        body = item.get("body", "") or ""
        content_text = f"{title} {body}".lower()

        matched_category = "problem_space"  # default
        matched_query = ""
        for query_text, category in query_category_map.items():
            if query_text.lower() in content_text or any(
                word in content_text for word in query_text.lower().split()
                if len(word) > 3
            ):
                matched_category = category
                matched_query = query_text
                break

        subreddit = item.get("communityName", "") or item.get("parsedCommunityName", "")

        signals.append({
            "platform": "reddit",
            "author": author,
            "title": title[:200],
            "text": body[:500],
            "url": item.get("url", ""),
            "content_type": data_type,
            "category": matched_category,
            "category_label": SIGNAL_CATEGORIES.get(matched_category, {}).get("label", matched_category),
            "score": item.get("upVotes", 0) or 0,
            "num_comments": item.get("numberOfComments", 0) or 0,
            "created_at": created_str,
            "query_matched": matched_query,
            "subreddit": subreddit,
        })

    print(f"[reddit] Total signals extracted: {len(signals)}", file=sys.stderr)
    return signals


# ---------------------------------------------------------------------------
# Deduplication & Scoring
# ---------------------------------------------------------------------------

def deduplicate_and_score(all_signals):
    """Deduplicate users across platforms and compute lead scores.

    Returns:
        users: dict[author_key] -> user summary
        signals: all signals with platform prefix on author
    """
    users = {}

    for signal in all_signals:
        platform = signal["platform"]
        author = signal["author"]
        # Create unique key per platform+author
        user_key = f"{platform}:{author}"

        if user_key not in users:
            users[user_key] = {
                "username": author,
                "platform": platform,
                "platforms_active": {platform},
                "signal_count": 0,
                "categories_seen": set(),
                "total_intent_score": 0,
                "total_engagement": 0,
                "subreddits": set(),
                "first_seen": signal.get("created_at", ""),
                "latest_seen": signal.get("created_at", ""),
                "sample_url": signal.get("url", ""),
            }

        user = users[user_key]
        user["signal_count"] += 1
        user["platforms_active"].add(platform)
        user["categories_seen"].add(signal["category"])
        user["total_engagement"] += signal.get("score", 0) + signal.get("num_comments", 0)

        # Add intent score based on category
        cat_score = SIGNAL_CATEGORIES.get(signal["category"], {}).get("intent_score", 5)
        user["total_intent_score"] += cat_score

        if signal.get("subreddit"):
            user["subreddits"].add(signal["subreddit"])

        # Track date range
        created = signal.get("created_at", "")
        if created:
            if not user["first_seen"] or created < user["first_seen"]:
                user["first_seen"] = created
            if not user["latest_seen"] or created > user["latest_seen"]:
                user["latest_seen"] = created

    # Check for cross-platform matches (same username on HN and Reddit)
    hn_users = {v["username"].lower(): k for k, v in users.items() if v["platform"] == "hackernews"}
    reddit_users = {v["username"].lower(): k for k, v in users.items() if v["platform"] == "reddit"}

    cross_platform = set()
    for name_lower in hn_users:
        if name_lower in reddit_users:
            cross_platform.add(name_lower)
            # Boost both entries
            users[hn_users[name_lower]]["total_intent_score"] += 10
            users[hn_users[name_lower]]["platforms_active"].add("reddit")
            users[reddit_users[name_lower]]["total_intent_score"] += 10
            users[reddit_users[name_lower]]["platforms_active"].add("hackernews")

    if cross_platform:
        print(f"[dedup] Found {len(cross_platform)} cross-platform username matches", file=sys.stderr)

    # Compute final composite score
    for user in users.values():
        # Composite: intent_score + signal_count bonus + category diversity bonus + cross-platform bonus
        category_bonus = len(user["categories_seen"]) * 2
        platform_bonus = 10 if len(user["platforms_active"]) > 1 else 0
        signal_bonus = min(user["signal_count"] * 2, 10)  # cap at 10
        user["composite_score"] = (
            user["total_intent_score"]
            + category_bonus
            + platform_bonus
            + signal_bonus
        )

    return users


# ---------------------------------------------------------------------------
# CSV Output
# ---------------------------------------------------------------------------

def build_csv(users, signals, hn_profiles, output_path, product_name=""):
    """Build two CSV files: _users.csv and _signals.csv."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Derive base name by stripping .csv extension
    output_base = str(output_path)
    if output_base.lower().endswith(".csv"):
        output_base = output_base[:-4]

    users_path = Path(f"{output_base}_users.csv")
    signals_path = Path(f"{output_base}_signals.csv")

    # Sort users by composite score
    sorted_users = sorted(users.values(), key=lambda u: u["composite_score"], reverse=True)

    # ===== FILE 1: USERS =====
    user_headers = [
        "username", "platform", "composite_score", "intent_score",
        "signal_count", "categories", "platforms_active",
        "subreddits", "hn_karma", "hn_bio",
        "total_engagement", "first_seen", "latest_seen", "sample_url",
    ]

    with open(users_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(user_headers)

        for user in sorted_users:
            hn_profile = hn_profiles.get(user["username"], {}) if user["platform"] == "hackernews" else {}

            row_data = [
                user["username"],
                user["platform"],
                user["composite_score"],
                user["total_intent_score"],
                user["signal_count"],
                ", ".join(sorted(user["categories_seen"])),
                ", ".join(sorted(user["platforms_active"])),
                ", ".join(sorted(user["subreddits"])) if user["subreddits"] else "",
                hn_profile.get("karma", ""),
                hn_profile.get("about", ""),
                user["total_engagement"],
                user["first_seen"][:10] if user["first_seen"] else "",
                user["latest_seen"][:10] if user["latest_seen"] else "",
                user["sample_url"],
            ]
            writer.writerow(row_data)

    # ===== FILE 2: SIGNALS =====
    signal_headers = [
        "platform", "author", "category", "category_label", "content_type",
        "title", "text", "subreddit", "score", "num_comments",
        "created_at", "query_matched", "url",
    ]

    # Sort signals by created_at desc
    sorted_signals = sorted(signals, key=lambda s: s.get("created_at", ""), reverse=True)

    with open(signals_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(signal_headers)

        for signal in sorted_signals:
            row_data = [
                signal["platform"],
                signal["author"],
                signal["category"],
                signal["category_label"],
                signal["content_type"],
                signal["title"][:150],
                signal["text"][:300],
                signal.get("subreddit", ""),
                signal.get("score", 0),
                signal.get("num_comments", 0),
                signal.get("created_at", "")[:10],
                signal.get("query_matched", ""),
                signal.get("url", ""),
            ]
            writer.writerow(row_data)

    print(f"\n[output] Saved to {users_path}", file=sys.stderr)
    print(f"[output] Users: {len(sorted_users)} rows", file=sys.stderr)
    print(f"[output] Saved to {signals_path}", file=sys.stderr)
    print(f"[output] Signals: {len(sorted_signals)} rows", file=sys.stderr)


# ---------------------------------------------------------------------------
# Main Pipeline
# ---------------------------------------------------------------------------

def run(queries_file, days=30, max_reddit_posts=50, max_reddit_comments=20,
        output=None, skip_reddit=False, skip_hn=False):
    """Main pipeline."""
    output = output or str(TMP_DIR / "community_signals.csv")
    ensure_tmp()

    # Load queries
    with open(queries_file) as f:
        config = json.load(f)

    product_name = config.get("product", "")
    queries = config.get("queries", [])
    subreddits = config.get("subreddits", [])

    if not queries:
        print("[error] No queries found in queries file", file=sys.stderr)
        sys.exit(1)

    print(f"[start] Product: {product_name}", file=sys.stderr)
    print(f"[start] {len(queries)} queries across {len(set(q['category'] for q in queries))} categories", file=sys.stderr)
    print(f"[start] Lookback: {days} days", file=sys.stderr)
    print(f"[start] Subreddits to scan: {', '.join(subreddits) if subreddits else 'global search only'}", file=sys.stderr)

    all_signals = []

    # --- Hacker News ---
    if not skip_hn:
        print(f"\n{'='*60}", file=sys.stderr)
        print("[hn] Starting Hacker News extraction...", file=sys.stderr)
        print(f"{'='*60}", file=sys.stderr)
        hn_signals = extract_hn_signals(queries, days=days)
        all_signals.extend(hn_signals)
    else:
        print("[hn] Skipped", file=sys.stderr)

    # --- Reddit ---
    if not skip_reddit:
        print(f"\n{'='*60}", file=sys.stderr)
        print("[reddit] Starting Reddit extraction...", file=sys.stderr)
        print(f"{'='*60}", file=sys.stderr)
        reddit_signals = reddit_search_apify(
            queries,
            subreddits=subreddits,
            days=days,
            max_posts_per_query=max_reddit_posts,
            max_comments_per_post=max_reddit_comments,
        )
        all_signals.extend(reddit_signals)
    else:
        print("[reddit] Skipped", file=sys.stderr)

    if not all_signals:
        print("[warning] No signals found across any platform", file=sys.stderr)
        sys.exit(0)

    print(f"\n[total] {len(all_signals)} signals collected", file=sys.stderr)

    # --- Deduplicate & Score ---
    print(f"\n{'='*60}", file=sys.stderr)
    print("[scoring] Deduplicating and scoring users...", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)
    users = deduplicate_and_score(all_signals)
    print(f"[scoring] {len(users)} unique users found", file=sys.stderr)

    # --- Enrich HN profiles ---
    hn_usernames = list(set(
        u["username"] for u in users.values() if u["platform"] == "hackernews"
    ))
    hn_profiles = {}
    if hn_usernames:
        print(f"\n[hn-profiles] Fetching {len(hn_usernames)} HN profiles...", file=sys.stderr)
        hn_profiles = enrich_hn_users(hn_usernames)

    # --- Build CSV ---
    build_csv(users, all_signals, hn_profiles, output, product_name)

    # --- Summary ---
    sorted_users = sorted(users.values(), key=lambda u: u["composite_score"], reverse=True)
    hn_count = sum(1 for u in users.values() if u["platform"] == "hackernews")
    reddit_count = sum(1 for u in users.values() if u["platform"] == "reddit")
    cross_platform = sum(1 for u in users.values() if len(u["platforms_active"]) > 1)
    high_intent = sum(1 for u in users.values() if u["composite_score"] >= 20)

    # Category breakdown
    category_counts = {}
    for signal in all_signals:
        cat = signal["category_label"]
        category_counts[cat] = category_counts.get(cat, 0) + 1

    # Subreddit breakdown
    subreddit_counts = {}
    for signal in all_signals:
        sub = signal.get("subreddit", "")
        if sub:
            subreddit_counts[sub] = subreddit_counts.get(sub, 0) + 1

    print(f"\n{'='*60}", file=sys.stderr)
    print(f"[summary] RESULTS", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)
    print(f"  Total signals: {len(all_signals)}", file=sys.stderr)
    print(f"  Unique users: {len(users)}", file=sys.stderr)
    print(f"  HN users: {hn_count}", file=sys.stderr)
    print(f"  Reddit users: {reddit_count}", file=sys.stderr)
    print(f"  Cross-platform matches: {cross_platform}", file=sys.stderr)
    print(f"  High-intent users (score >= 20): {high_intent}", file=sys.stderr)
    print(f"\n  Signal categories:", file=sys.stderr)
    for cat, count in sorted(category_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"    {cat}: {count}", file=sys.stderr)
    if subreddit_counts:
        print(f"\n  Top subreddits:", file=sys.stderr)
        for sub, count in sorted(subreddit_counts.items(), key=lambda x: x[1], reverse=True)[:10]:
            print(f"    {sub}: {count}", file=sys.stderr)
    print(f"\n  Output: {output}", file=sys.stderr)
    print(f"{'='*60}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="Community Signals — Developer Forum Lead Extraction"
    )
    parser.add_argument(
        "--queries", required=True,
        help="Path to queries JSON file (generated by the skill)"
    )
    parser.add_argument(
        "--days", type=int, default=30,
        help="Lookback period in days (default: 30)"
    )
    parser.add_argument(
        "--max-reddit-posts", type=int, default=50,
        help="Max Reddit posts per search query (default: 50)"
    )
    parser.add_argument(
        "--max-reddit-comments", type=int, default=20,
        help="Max comments to fetch per Reddit post (default: 20)"
    )
    parser.add_argument(
        "--skip-reddit", action="store_true",
        help="Skip Reddit (only search HN)"
    )
    parser.add_argument(
        "--skip-hn", action="store_true",
        help="Skip Hacker News (only search Reddit)"
    )
    parser.add_argument(
        "--output", default=None,
        help="Output .csv path (default: .tmp/community_signals.csv)"
    )
    args = parser.parse_args()

    run(
        queries_file=args.queries,
        days=args.days,
        max_reddit_posts=args.max_reddit_posts,
        max_reddit_comments=args.max_reddit_comments,
        output=args.output,
        skip_reddit=args.skip_reddit,
        skip_hn=args.skip_hn,
    )


if __name__ == "__main__":
    main()
